name: New Issues
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Labeler
        uses: ${{ secrets.GITHUB_WORKSPACE }}/.github/actions/issues
